### ISSUE TITLE
I am working on a awesome-python-htmx, seeking your feedback

### ISSUE THREAD

**Issue by benjamin-kirkbride** [sponsfreixes/jinja2-fragments#11]
@tataraba and I at PyCon this year got together and brainstormed a new Web Stack that we are calling PyHAT (Python, htmx, ASGI, TailwindCSS). The first thing we set out to do is create [awesome-python-htmx](https://github.com/PyHAT-stack/awesome-python-htmx/blob/main/README.md); a collection of active tools/libraries/projects in that space.

This project is an obvious thing to include, and indeed was part of the inspiration to do this, so I did so. I'd appreciate feedback if you have any on it's inclusion.

In addition to that, if you could also participate in https://github.com/PyHAT-stack/awesome-python-htmx/discussions/1 that would be greatly appreciated!

Related to #8

**Comment by sponsfreixes** [comment]
As I said on the comments of another project, that's great! Very happy for jinja2-fragments to be part of that!
