### ISSUE TITLE
Getting New Lines

### ISSUE THREAD

**Issue by nicktids** [sponsfreixes/jinja2-fragments#18]
Using 
fastapi[all]==0.103.1
jinja2-fragments==1.0.0

I'm getting lots of \n new lines all over the block when using the Jinja2Blocks
```
{% block test_items %}
        <div id="items">

            {% for item in items %}
                <li>{{ item }}</li>
            {% endfor %}
        </div>
{% endblock %}
```

Output and it is stringified with quotations
```
"\n
\n
\n\n \n
 Item1
\n \n
 Item2
\n \n
\n
\n"
```

but if I put this in a partial html file with just 
```
<ul>
    {% for item in items %}
        <li>{{ item }}</li>
    {% endfor %}
</ul>

```
Then comes out perfect

- Item1
- Item2

Can you understand why it might be creating extra line items.

Using python3.11-bullseye docker container

**Comment by sponsfreixes** [comment]
We recently [changed the behavior for FastAPI to return a Response object instead of pure text](https://github.com/sponsfreixes/jinja2-fragments/pull/16), but I never released a packaged version with that change. I just did that and [pushed it to PyPi as 1.1.0](https://pypi.org/project/jinja2-fragments/#history). Could you download the new version and check if that works as you would expect, please?

**Comment by senpos** [comment]
Hi!

> Then comes out perfect

Can you show the code for it, please?

No matter what I do, I get these extra newlines and this behavior is expected / on par with the default Jinja2 environment. The FastAPI (Starlette) templating works similarly.

**Code**
```python
from fastapi import FastAPI
from fastapi.requests import Request
from fastapi.templating import Jinja2Templates
from jinja2_fragments.fastapi import Jinja2Blocks

app = FastAPI()

templ_default = Jinja2Templates(directory="templates")
templ_blocks = Jinja2Blocks(directory="templates")


@app.get("/blocks/full_page")
async def full_page_blocks(request: Request):
    return templ_blocks.TemplateResponse(
        "items.html.jinja",
        {"request": request, "items": range(5)},
    )


@app.get("/blocks/items")
async def only_content_blocks(request: Request):
    return templ_blocks.TemplateResponse(
        "items.html.jinja",
        {"request": request, "items": range(5)},
        block_name="items",
    )


@app.get("/default/full_page")
async def full_page_default(request: Request):
    return templ_default.TemplateResponse(
        "items.html.jinja",
        {"request": request, "items": range(5)},
    )
```

**Tempaltes**
<details><summary>base.html.jinja</summary>
<p>

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>This is the title</title>
</head>
<body>
    <h1>This is a header</h1>
    {% block items %}
    {% endblock %}
</body>
</html>
```

</p>
</details> 

<details><summary>items.html.jinja</summary>
<p>

```html
{% extends "base.html.jinja" %}
{% block items %}
<ul>
    {% for item in items %}
        <li>{{ item }}</li>
    {% endfor %}
</ul>
{% endblock %}
```

</p>
</details> 

**Rendered HTML**
<details><summary>blocks_full_page.html</summary>
<p>

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>This is the title</title>
</head>
<body>
    <h1>This is a header</h1>
    
<ul>
    
        <li>0</li>
    
        <li>1</li>
    
        <li>2</li>
    
        <li>3</li>
    
        <li>4</li>
    
</ul>

</body>
</html>
```

</p>
</details> 

<details><summary>blocks_items.html</summary>
<p>

```
<ul>
    
        <li>0</li>
    
        <li>1</li>
    
        <li>2</li>
    
        <li>3</li>
    
        <li>4</li>
    
</ul>
```

</p>
</details> 

<details><summary>default_full_page.html</summary>
<p>

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>This is the title</title>
</head>
<body>
    <h1>This is a header</h1>
    
<ul>
    
        <li>0</li>
    
        <li>1</li>
    
        <li>2</li>
    
        <li>3</li>
    
        <li>4</li>
    
</ul>

</body>
</html>
```

</p>
</details> 

If you don't want that extra whitespace, you may want to check [this](https://jinja.palletsprojects.com/en/3.1.x/templates/#whitespace-control).

Here's how it looks:
```python
templ_blocks = Jinja2Blocks(
    directory="templates",
    trim_blocks=True,
)
```
<details><summary>blocks_full_page.html (trim)</summary>
<p>

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>This is the title</title>
</head>
<body>
    <h1>This is a header</h1>
    <ul>
            <li>0</li>
            <li>1</li>
            <li>2</li>
            <li>3</li>
            <li>4</li>
    </ul>
</body>
</html>
```

</p>
</details> 

There's also `lstrip_block=True` which removes even more space.

**Comment by sponsfreixes** [comment]
Closing as @senpos provided an explanation of the behavior, and it's consistent with default jinja output.
