### ISSUE TITLE
Please add type annotations and py.typed marker.

### ISSUE THREAD

**Issue by wojciech-mazur-mlg** [sponsfreixes/jinja2-fragments#20]
I love this library, it's very usefull!
I see it mosty supports type annotations, but there are some places where they're missing.
Unfortunately it doesn't contain `py.typed` marker file, so mypy is throwing an error.

Could you add this file and missing type annotations in future release?

Thanks in advance!

**Comment by sponsfreixes** [comment]
The file has been added to most recent release (1.2.0).

**Comment by wojciech-mazur-mlg** [comment]
Perfect, thank you!

**Comment by wojciech-mazur-mlg** [comment]
It looks like py.typed file is present in code repo, but it's not installed from PyPI. It's not present in released packages.
Probably you have to include this file explicitly in setup.py.

Some hints:
https://jugmac00.github.io/blog/bite-my-shiny-type-annotated-library/
https://blog.whtsky.me/tech/2021/dont-forget-py.typed-for-your-typed-python-package/

**Comment by sponsfreixes** [comment]
My bad, I should have checked! Fixed on 1.2.1!

**Comment by wojciech-mazur-mlg** [comment]
Thank you. It works great now!
