### ISSUE TITLE
Is Django supported?

### ISSUE THREAD

**Issue by wshayes** [sponsfreixes/jinja2-fragments#3]

**Comment by sponsfreixes** [comment]
I think it could be used with Django, but you might be missing whatever integrations Django currently has with Jinja2. The project would welcome a contribution to implement that!

**Comment by tataraba** [comment]
Just worked on a Django project recently and was looking for a similar solution. Found this:

[Django Render Block](https://github.com/clokep/django-render-block)
[https://pypi.org/project/django-render-block/](https://pypi.org/project/django-render-block/)

It works fairly similar. For example, if you have a view that is accepting an htmx request, it looks something like this:

```py
def random_view(request):
    some_objects = SomeObject.objects.all()
    if request.headers.get("HX-Request"):
        html = render_block_to_string(
            "slideshow/index.html",                    # name of the template
            "block_name",                                   # name of block name to be rendered
            {"some_objects":  some_objects},     # additional context (accessible through your block
            request=request
        )
        return HttpResponse(html)
```

Only the "block_name" is sent (and rendered) in the case of an htmx request.

Hope that helps. (Sorry so late to responding)

**Comment by sponsfreixes** [comment]
django-render-block is a good alternative to use with Django as it has partial support for jinja. It seems you only need to be mindful of this limitation:

> Partially supports the [Jinja2](http://jinja.pocoo.org/) engine: it does not currently process the extends tag.

**Comment by sponsfreixes** [comment]
Closing as the original question has been responded.
