### ISSUE TITLE
Response headers are ignored when rendering a block

### ISSUE THREAD

**Issue by amjith** [sponsfreixes/jinja2-fragments#6]
I am trying to send a [response header](https://htmx.org/headers/hx-replace-url/) when I return the response to render a block. But it looks like the code path doesn't pass through the response headers for rendering a block. 

Can this be added? I'm happy to take a stab at a PR if you can give me a hint as to how to do this.

**Comment by amjith** [comment]
I forgot to mention, I'm using FastAPI with jinja2_fragments.

**Comment by sponsfreixes** [comment]
Hi @amjith. Could you post a minimal code example with the issue? I want to make sure I am understanding the problem.

**Comment by sponsfreixes** [comment]
Closing as didn't get any reply.
