### ISSUE TITLE
Discussion of an Alternative: forge-htmx

### ISSUE THREAD

**Issue by benjamin-kirkbride** [sponsfreixes/jinja2-fragments#8]
This is an library for Django that covers a lot of the same ground as jinja2-fragments: https://www.forgepackages.com/docs/forge-htmx/

Curious what everyone's thoughts are on what we could learn from it.

**Comment by sponsfreixes** [comment]
After a first reading, it seems an interesting project, but I don't see any ideas to port to jinja2-fragments. The features seem to be htmx specific, and while jinja2-fragments was born from the idea of using with htmx, it's not coupled with it. I'll go through it again in a few days and give it more thought, and if anybody has a suggestion/idea, it's very welcome!
